FROM centos:7.9.2009

MAINTAINER jiahao <jiajiahaol@foxmail.com>

RUN curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo && \
    yum clean all && yum makecache && \
    yum update -y


RUN yum install -y epel-release && \
    yum install -y yum-utils && \
    yum install -y https://mirrors.aliyun.com/ius/ius-release-el7.rpm && \
    yum install -y \
        python36u python36u-pip python36u-devel \
        wget \
        && yum clean all

RUN yum install -y java-11-openjdk
